# АНСАМБЛИ МОДЕЛЕЙ

In [0]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
!pip install jupyterthemes
from jupyterthemes import jtplot
from sklearn.metrics import auc, roc_curve, roc_auc_score
%matplotlib inline
jtplot.style()

Collecting jupyterthemes
  Downloading https://files.pythonhosted.org/packages/8a/08/9dee6dfd7f2aad6c30282d55c8f495b4dc1e4747b4e2bdbeb80572ddf312/jupyterthemes-0.20.0-py2.py3-none-any.whl (7.0MB)
     |████████████████████████████████| 7.0MB 1.4MB/s
Collecting lesscpy>=0.11.2
  Downloading https://files.pythonhosted.org/packages/f8/d2/665cda6614e3556eaeb7553a3a2963624c2e3bc9636777a1bb654b87b027/lesscpy-0.14.0-py2.py3-none-any.whl (46kB)
     |████████████████████████████████| 51kB 6.4MB/s
Requirement already satisfied: matplotlib>=1.4.3 in /usr/local/lib/python3.6/dist-packages (from jupyterthemes) (3.2.1)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.6/dist-packages (from jupyterthemes) (4.6.3)
Requirement already satisfied: ipython>=5.4.1 in /usr/local/lib/python3.6/dist-packages (from jupyterthemes) (5.5.0)
Collecting notebook>=5.6.0
  Downloading https://files.pythonhosted.org/packages/b1/f1/0a67f09ef53a342403ffa66646ee39273e0ac79ffa5de5dbe2f3e28b5bdf/notebook-6.0.3-py3-none-any.whl (9.7MB)
     |████████████████████████████████| 9.7MB 39.8MB/s
Collecting ply
  Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)
     |████████████████████████████████| 51kB 6.4MB/s
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from lesscpy>=0.11.2->jupyterthemes) (1.12.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.4.3->jupyterthemes) (2.4.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.4.3->jupyterthemes) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.4.3->jupyterthemes) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.4.3->jupyterthemes) (1.1.0)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.4.3->jupyterthemes) (1.18.2)
Requirement already satisfied: traitlets in /usr/local/lib/python3.6/dist-packages (from jupyter-core->jupyterthemes) (4.3.3)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from ipython>=5.4.1->jupyterthemes) (4.8.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from ipython>=5.4.1->jupyterthemes) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from ipython>=5.4.1->jupyterthemes) (1.0.18)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from ipython>=5.4.1->jupyterthemes) (4.4.2)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.6/dist-packages (from ipython>=5.4.1->jupyterthemes) (0.8.1)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/dist-packages (from ipython>=5.4.1->jupyterthemes) (2.1.3)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/dist-packages (from ipython>=5.4.1->jupyterthemes) (46.0.0)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (17.0.0)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (0.7.1)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (5.6.1)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (4.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (2.11.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (1.5.0)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (0.8.3)
Requirement already satisfied: nbformat in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (5.0.4)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (0.2.0)
Requirement already satisfied: jupyter-client>=5.3.4 in /usr/local/lib/python3.6/dist-packages (from notebook>=5.6.0->jupyterthemes) (5.3.4)
Collecting tornado>=5.0
  Downloading https://files.pythonhosted.org/packages/95/84/119a46d494f008969bf0c775cb2c6b3579d3c4cc1bb1b41a022aa93ee242/tornado-6.0.4.tar.gz (496kB)
     |████████████████████████████████| 501kB 53.5MB/s
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/dist-packages (from pexpect; sys_platform != "win32"->ipython>=5.4.1->jupyterthemes) (0.6.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=5.4.1->jupyterthemes) (0.1.9)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.8.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (3.1.3)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.6.0)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.3)
Requirement already satisfied: testpath in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.4.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (1.4.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2->notebook>=5.6.0->jupyterthemes) (1.1.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.6/dist-packages (from nbformat->notebook>=5.6.0->jupyterthemes) (2.6.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/dist-packages (from bleach->nbconvert->notebook>=5.6.0->jupyterthemes) (0.5.1)
Building wheels for collected packages: tornado
  Building wheel for tornado (setup.py) ... done
  Created wheel for tornado: filename=tornado-6.0.4-cp36-cp36m-linux_x86_64.whl size=427641 sha256=d0f97d52e7cea310be231a085154273302f919b97673e5ff5ab706502789f2c8
  Stored in directory: /root/.cache/pip/wheels/93/84/2f/409c7b2bb3afc3aa727f7ee8787975e0793f74d1165f4d0104
Successfully built tornado
ERROR: google-colab 1.0.0 has requirement notebook~=5.2.0, but you'll have notebook 6.0.3 which is incompatible.
ERROR: google-colab 1.0.0 has requirement tornado~=4.5.0, but you'll have tornado 6.0.4 which is incompatible.
Installing collected packages: ply, lesscpy, tornado, notebook, jupyterthemes
  Found existing installation: tornado 4.5.3
    Uninstalling tornado-4.5.3:
      Successfully uninstalled tornado-4.5.3
  Found existing installation: notebook 5.2.2
    Uninstalling notebook-5.2.2:
      Successfully uninstalled notebook-5.2.2
Successfully installed jupyterthemes-0.20.0 lesscpy-0.14.0 notebook-6.0.3 ply-3.11 tornado-6.0.4

# Домашняя работа

1. Теперь решаем задачу регрессии - предскажем цены на недвижимость. Использовать датасет https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data (train.csv)
2. Данных немного, поэтому необходимо использовать 10-fold кросс-валидацию для оценки качества моделей
3. Построить случайный лес, вывести важность признаков
4. Обучить стекинг как минимум 3х моделей, использовать хотя бы 1 линейную модель и 1 нелинейную
5. Для валидации модели 2-го уровня использовать отдельный hold-out датасет, как на занятии
6. Показать, что использование ансамблей моделей действительно улучшает качество (стекинг vs другие модели сравнивать на hold-out)
7. В качестве решения:
    Jupyter notebook с кодом, комментариями и графиками

In [0]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, median_absolute_error, r2_score

In [0]:
data_s=pd.read_csv("train2.csv")
data_s.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [0]:
#ddd=data_s['SalePrice']
#ddd

In [0]:
data_s.sort_values('SalePrice',inplace=True)
data_s.head()

      Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
495  496          30  C (all)  ...        WD        Abnorml     34900
916  917          20  C (all)  ...        WD        Abnorml     35311
968  969          50       RM  ...        WD        Abnorml     37900
533  534          20       RL  ...        WD         Normal     39300
30    31          70  C (all)  ...        WD         Normal     40000

[5 rows x 81 columns]

In [0]:
#data_s.info()

In [0]:
cols=['FireplaceQu','PoolQC','Fence','MiscFeature']
data_s.drop(cols,inplace=True, axis=1)

In [0]:
#from sklearn.preprocessing import LabelEncoder

In [0]:
#ppp=['Alley','MasVnrType']
#data_s.fillna("yy", inplace=True)

In [0]:

data_s=pd.get_dummies(data_s)
#data_s.fillna(0, inplace=True)
data_s.fillna(0, inplace=True)
#ata_s=data_s.iloc[:,:36]
#data_s['SalePrice']=ddd
data_s.head()

      Id  MSSubClass  ...  SaleCondition_Normal  SaleCondition_Partial
495  496          30  ...                     0                      0
916  917          20  ...                     0                      0
968  969          50  ...                     0                      0
533  534          20  ...                     1                      0
30    31          70  ...                     1                      0

[5 rows x 274 columns]

In [0]:
#data_s[['MSZoning','Street','Alley']]=data_s[['MSZoning','Street','Alley']].apply(LabelEncoder().fit_transform)
#data_s.head()

In [0]:
data_s.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 495 to 691
Columns: 274 entries, Id to SaleCondition_Partial
dtypes: float64(3), int64(35), uint8(236)
memory usage: 781.3 KB

In [0]:

#data_s.groupby(['LotArea']).agg(len)

In [0]:
data_s.describe().transpose()

                        count          mean  ...       75%       max
Id                     1460.0    730.500000  ...   1095.25    1460.0
MSSubClass             1460.0     56.897260  ...     70.00     190.0
LotFrontage            1460.0     57.623288  ...     79.00     313.0
LotArea                1460.0  10516.828082  ...  11601.50  215245.0
OverallQual            1460.0      6.099315  ...      7.00      10.0
...                       ...           ...  ...       ...       ...
SaleCondition_AdjLand  1460.0      0.002740  ...      0.00       1.0
SaleCondition_Alloca   1460.0      0.008219  ...      0.00       1.0
SaleCondition_Family   1460.0      0.013699  ...      0.00       1.0
SaleCondition_Normal   1460.0      0.820548  ...      1.00       1.0
SaleCondition_Partial  1460.0      0.085616  ...      0.00       1.0

[274 rows x 8 columns]

In [0]:
#data_s.fillna(0, inplace=False)

In [0]:
data_s.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 495 to 691
Columns: 274 entries, Id to SaleCondition_Partial
dtypes: float64(3), int64(35), uint8(236)
memory usage: 781.3 KB

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(data_s.drop('SalePrice', inplace=False, axis=1), data_s['SalePrice'], test_size=0.3)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [0]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

clf_data = RandomForestRegressor(n_estimators=100, max_depth=20, min_samples_leaf=20, max_features=0.5, n_jobs=-1)
clf_data.fit(X_train, y_train)   

y_pr=clf_data.predict(X_test)
y_pr_tr=clf_data.predict(X_train)

In [0]:

clf_data.score(X_test, y_test)

0.7877225698505798

In [0]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf_data, X_train, y_train, cv=10)
scores

array([0.80643268, 0.83852627, 0.85335515, 0.74314536, 0.84636997,
       0.82651853, 0.72218121, 0.79109574, 0.87186424, 0.80290356])

In [0]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf_data, X_test, y_test, cv=10)
scores

array([0.82600602, 0.85570385, 0.79308142, 0.91382063, 0.67971877,
       0.65348494, 0.6734477 , 0.6801604 , 0.82095055, 0.56079897])

In [0]:
print(mean_squared_error(y_test, y_pr))
print(r2_score(y_test, y_pr))

1608340443.0611644
0.7877225698505798

In [0]:
X_test.head()

      Id  MSSubClass  ...  SaleCondition_Normal  SaleCondition_Partial
900  901          20  ...                     1                      0
628  629          60  ...                     0                      0
351  352         120  ...                     0                      0
405  406          20  ...                     1                      0
475  476          20  ...                     1                      0

[5 rows x 273 columns]

In [0]:
data_s.head()

      Id  MSSubClass  ...  SaleCondition_Normal  SaleCondition_Partial
495  496          30  ...                     0                      0
916  917          20  ...                     0                      0
968  969          50  ...                     0                      0
533  534          20  ...                     1                      0
30    31          70  ...                     1                      0

[5 rows x 274 columns]

In [0]:
#cols = [14,17,29]

#X_test.drop(X_test.columns[cols,inplace=False, axis=1)

In [0]:
#data_s.iloc[:,cols].head()
#data_s.head()

In [0]:
X_train.iloc[:5,:25].transpose()

                 747     1323     928      891     1387
Id              748.0  1324.0    929.0    892.0  1388.0
MSSubClass       70.0    30.0     20.0     60.0    50.0
LotFrontage      65.0    50.0      0.0     70.0    60.0
LotArea       11700.0  5330.0  11838.0  11184.0  8520.0
OverallQual       7.0     4.0      8.0      6.0     6.0
OverallCond       7.0     7.0      5.0      5.0     7.0
YearBuilt      1880.0  1940.0   2001.0   1978.0  1916.0
YearRemodAdd   2003.0  1950.0   2001.0   1978.0  1950.0
MasVnrArea        0.0     0.0      0.0     92.0     0.0
BsmtFinSF1        0.0   280.0      0.0    226.0   168.0
BsmtFinSF2        0.0     0.0      0.0    500.0   546.0
BsmtUnfSF      1240.0   140.0   1753.0    192.0     0.0
TotalBsmtSF    1240.0   420.0   1753.0    918.0   714.0
1stFlrSF       1320.0   708.0   1788.0    918.0  1664.0
2ndFlrSF       1320.0     0.0      0.0    765.0   862.0
LowQualFinSF      0.0     0.0      0.0      0.0     0.0
GrLivArea      2640.0   708.0   1788.0   1683.0  2526.0
BsmtFullBath      0.0     0.0      0.0      0.0     0.0
BsmtHalfBath      0.0     0.0      0.0      0.0     0.0
FullBath          1.0     1.0      2.0      2.0     2.0
HalfBath          1.0     0.0      0.0      1.0     0.0
BedroomAbvGr      4.0     2.0      3.0      3.0     5.0
KitchenAbvGr      1.0     1.0      1.0      1.0     1.0
TotRmsAbvGrd      8.0     5.0      7.0      7.0    10.0
Fireplaces        1.0     0.0      1.0      1.0     1.0

In [0]:

print(clf_data.feature_importances_[:5])

[3.13737942e-04 1.63173919e-03 8.79222204e-04 6.95737991e-03
 3.68866855e-01]

In [0]:
from sklearn.linear_model import LogisticRegression
clf_lr = LogisticRegression(penalty='l2', C=0.1)

clf_lr.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_log=clf_lr.predict(X_test)

In [0]:
clf_lr.score(X_test, y_test)

0.00684931506849315

In [0]:
print(mean_squared_error(y_test, y_log))
print(r2_score(y_test, y_log))

4886492543.221461
0.3550544077937431

In [0]:
from sklearn.linear_model import LinearRegression
clf_lin = LinearRegression()

clf_lin.fit(X_train, y_train)

y_lin=clf_lr.predict(X_test)

In [0]:
clf_lin.score(X_test, y_test)

0.8481772690455044

In [0]:
print(mean_squared_error(y_test, y_lin))
print(r2_score(y_test, y_lin))

4886492543.221461
0.3550544077937431

In [0]:
y_meta=(y_lin+y_log+y_pr)/3

In [0]:
print(mean_squared_error(y_test, y_meta))
print(r2_score(y_test, y_meta))

3176790063.4630146
0.5807101452273208

In [0]:
from sklearn.ensemble import BaggingRegressor

bag_reg = BaggingRegressor(n_estimators=20, n_jobs=-1)
bag_reg.fit(X_train, y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=False,
                 max_features=1.0, max_samples=1.0, n_estimators=20, n_jobs=-1,
                 oob_score=False, random_state=None, verbose=0,
                 warm_start=False)

In [0]:
y_pred_test_bag = bag_reg.predict(X_test)

In [0]:
print(mean_squared_error(y_test, y_pred_test_bag))
print(r2_score(y_test, y_pred_test_bag))

1068298570.0552169
0.8590002035564074

y_pred_train_tr=rand

In [0]:
y_pred_train_tr=clf_data.predict(X_train)
y_pred_train_lg=clf_lr.predict(X_train)
y_pred_train_lin=clf_lin.predict(X_train)

In [0]:

X_train_meta=pd.DataFrame({'tr':(y_pred_train_tr),'lg':(y_pred_train_lg),'lin':(y_pred_train_lin)})
X_train_meta.head()

              tr      lg            lin
0  248832.317417  200000  255992.318128
1   97714.227093   60000  106950.956938
2  258549.392533  190000  240323.231812
3  169955.771671  154000  168501.798072
4  179690.522877  136000  156096.309454

In [0]:
y_pred_test_tr=clf_data.predict(X_test)
y_pred_test_lg=clf_lr.predict(X_test)
y_pred_test_lin=clf_lin.predict(X_test)

In [0]:

X_test_meta=pd.DataFrame({'tr':(y_pred_test_tr),'lg':(y_pred_test_lg),'lin':(y_pred_test_lin)})
X_test_meta.head()

              tr      lg            lin
0  114388.075090  140000  104326.203806
1  179221.914711  200000  137519.903951
2  193470.521791  148500  186259.822825
3  172828.392728  220000  165755.178587
4  136376.912479  125000  152453.643766

In [0]:
y_train

747     265979
1323     82500
928     236500
891     172500
1387    136000
         ...
1257     99900
69      225000
1066    178000
752     217000
990     348000
Name: SalePrice, Length: 1022, dtype: int64

In [0]:
clf_lr_meta = LogisticRegression()
clf_lr_meta.fit(X_train_meta, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred_meta_test = clf_lr_meta.predict_proba(X_test_meta)[:,1]

In [0]:
print(mean_squared_error(y_test, y_pred_meta_test))
print(r2_score(y_test, y_pred_meta_test))

41133898940.14772
-4.429073425786167

Не очень понимаю, почему в последнем случае получаю такой результат(